apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260607-224634-0mjamcmoa5t6-service
spec:
  selector:
    app: enterprise-system-20260607-224634-0mjamcmoa5t6
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
